/*
Class Name  : FindTheDifference
Description : This class consists of the solution for FindTheDifference.
Created Date: Dec 18, 2022
Author      : Chandra Sekhar Reddy Muthumula
Website Link: https://leetcode.com/problems/find-the-difference/description/
Modification Log: 
Date					Name                                            Description
Dec 18, 2022			Chandra Sekhar Reddy Muthumula					Added Class FindTheDifference 
Dec 18, 2022			Chandra Sekhar Reddy Muthumula					Added findTheDifference
--------------------------------------------------------------------------------------------------
389. Find the Difference
Easy
3.4K
403
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
------------------------------------------------------------------------------------------------------
*/
package Problems.FindTheDifference;

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        /*  
         * TC : O(N)
         * SC : O(1)
        */
        int sLen = s.length();
        int tLen = t.length();
        
        int[] freq = new int[26];
        for (int i = 0; i < sLen; i++) {
            freq[s.charAt(i) - 'a']++;
            freq[t.charAt(i) - 'a']--;
        }

        freq[t.charAt(tLen - 1) - 'a']--;

        for (int  i = 0; i < 26; i++) {
            if(freq[i] < 0) {
               return (char)(i + 'a');
            }
        }
        return 'a';
    }
}